---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: default
    inherits: 
    description: 
  fields:
  - vmname:
      value: "/Common/VM/Provisioning/Naming/vmname_with_domain_name"
