---
object_type: method
version: 1.0
object:
  attributes:
    name: get_configure_vm_network_and_ip_parameters
    display_name: 
    description: 
    scope: instance
    language: ruby
    location: inline
  inputs: []
