---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: get_available_destination_networks
    inherits: 
    description: 
  fields:
  - execute:
      value: get_available_networks(network_purpose => 'destination')
