---
object_type: method
version: 1.0
object:
  attributes:
    name: get_existing_tags_on_selected_lans
    display_name: 
    description: 
    scope: instance
    language: ruby
    location: inline
  inputs:
  - field:
      aetype: 
      name: shared_only
      display_name: 
      datatype: boolean
      priority: 1
      owner: 
      default_value: 'true'
      substitute: false
      message: create
      visibility: 
      collect: 
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 
      on_error: 
      max_retries: 
      max_time: 
