---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: get_existing_tags_on_selected_lans_shared_only
    inherits: 
    description: 
  fields:
  - execute:
      value: get_existing_tags_on_selected_lans(shared_only => 'true')
