---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: get_lans_by_name
    inherits: 
    description: 
  fields:
  - execute:
      value: get_lans(values_key => 'name')
