---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: Configure VM Network and IP
    name: ConfigureVMNetworkAndIP
    inherits: 
    description: 
  fields:
  - job_template_name:
      value: Sandbox | Configure VM Network and IP
  - GetJobParameters:
      value: get_configure_vm_network_and_ip_parameters
