---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: Configure VM Network and IP
    name: ConfigureVMNetworkAndIP
    inherits: 
    description: 
  fields:
  - job_template_name:
      value: Configure VM Network and IP
  - GetJobParameters:
      value: "/AutomationManagement/AnsibleTower/Operations/Methods/get_configure_vm_network_and_ip_parameters"
      collect: "/dialog_param_vm_network_ip4 = dialog_param_vm_network_ip4; /dialog_param_vm_network_ip4_netmask_prefix
        = dialog_param_vm_network_ip4_netmask_prefix; /dialog_param_vm_network_gw4
        = dialog_param_vm_network_gw4; /dialog_param_vm_network_dns4 = dialog_param_vm_network_dns4;
        /dialog_param_virt_network = dialog_param_virt_network; /dialog_param_vsphere_network_type
        = dialog_param_vsphere_network_type; /dialog_param_vsphere_hostname = dialog_param_vsphere_hostname;
        /dialog_param_vsphere_datacenter = dialog_param_vsphere_datacenter; /dialog_param_vsphere_username
        = dialog_param_vsphere_username; /dialog_param_vsphere_password = dialog_param_vsphere_password;
        /dialog_param_vsphere_network_type = dialog_param_vsphere_network_type; /dialog_param_ovirt_url
        = dialog_param_ovirt_url; /dialog_param_ovirt_username = dialog_param_ovirt_username;
        /dialog_param_ovirt_password = dialog_param_ovirt_password"
