---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: get_configure_vm_network_and_ip_parameters
    inherits: 
    description: 
  fields:
  - execute:
      value: get_configure_vm_network_and_ip_parameters
