---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: WaitForVMHostnames
    inherits: 
    description: 
  fields:
  - execute:
      value: wait_for_vm_hostnames
