---
object_type: method
version: 1.0
object:
  attributes:
    name: resize_disk
    display_name: ResizeDisk
    description: 
    scope: instance
    language: ruby
    location: inline
  inputs: []
