---
object_type: method
version: 1.0
object:
  attributes:
    name: wait_for_vm_mac_addresses
    display_name: WaitForVMMACAddresses
    description: 
    scope: instance
    language: ruby
    location: inline
    options: {}
  inputs: []
