---
object_type: method
version: 1.0
object:
  attributes:
    name: wait_for_vm_ip_addresses
    display_name: WaitForVMIPAddresses
    description: 
    scope: instance
    language: ruby
    location: inline
  inputs: []
