---
object_type: class
version: 1.0
object:
  attributes:
    description: 
    display_name: 
    name: MigrateVMNetwork
    type: 
    inherits: 
    visibility: 
    owner: 
  schema:
  - field:
      aetype: state
      name: ReleaseIPAddress
      display_name: 
      datatype: string
      priority: 1
      owner: 
      default_value: 
      substitute: true
      message: create
      visibility: 
      collect: 
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 'update_status(message => ''Migrate VM Network: Released current IP
        address'')'
      on_error: 'update_status(message => ''Migrate VM Network: Error releasing IP
        address'')'
      max_retries: 
      max_time: 
  - field:
      aetype: state
      name: AcquireIPAddress
      display_name: 
      datatype: string
      priority: 2
      owner: 
      default_value: 
      substitute: true
      message: create
      visibility: 
      collect: 
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 'update_status(message => ''Migrate VM Network: Acquired new IP address'')'
      on_error: 'update_status(message => ''Migrate VM Network: Error acquiring IP
        address'')'
      max_retries: 
      max_time: 
  - field:
      aetype: state
      name: ConfigureVMNetworkAndIP
      display_name: 
      datatype: string
      priority: 3
      owner: 
      default_value: 
      substitute: true
      message: create
      visibility: 
      collect: 
      scope: 
      description: 
      condition: 
      on_entry: 
      on_exit: 'update_status(message => ''Migrate VM Network: Configured new VM network
        and IP address'')'
      on_error: 'update_status(message => ''Migrate VM Network: Error configuring
        new VM network and IP address'')'
      max_retries: 
      max_time: 
