---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: default
    inherits: 
    description: 
  fields:
  - ReleaseIPAddress:
      value: "/Infrastructure/Network/Operations/Methods/ReleaseIPAddress"
  - AcquireIPAddress:
      value: "/Infrastructure/Network/Operations/Methods/AcquireIPAddress?network_name_parameter_name=destination_network"
      collect: "/destination_ip_address = acquired_ip_address"
  - ConfigureVMNetworkAndIP:
      value: "/AutomationManagement/AnsibleTower/Operations/JobTemplate/ConfigureVMNetworkAndIP"
